GreyTeam2020/GoOutSafe_Primer2020

README.md, monolith/app.py, monolith/auth.py, monolith/background.py, monolith/classes/restaurant.py, monolith/classes/table.py, monolith/classes/tests/test_restaurant.py, monolith/database.py, monolith/forms.py, monolith/views/auth.py, monolith/views/home.py, monolith/views/restaurants.py, monolith/views/users.py, requirements.txt
This PR adds [black](https://github.com/psf/black) to format the code without worry about it and in addition, I added a draft of the readme description for all people that are starting with the project
=> Formatting code and update readme (draft version)

.travis.yml, Dockerfile, docker-compose.yaml
~Travis need other works but~ Travis return a green lamp and in addition, it is possible play with `docker-compose up`
=> Added support Docker and travis

monolith/templates/create_restaurant.html, monolith/templates/index.html
=> interface restaurant

monolith/templates/index.html
More information about restaurants in the list
=> list of restaurants

monolith/app.py, monolith/database.py
Credentials of Health organization
=> health organizazion

monolith/templates/create_restaurant.html, monolith/templates/create_user.html, monolith/templates/index.html, monolith/templates/login.html, monolith/views/auth.py, monolith/views/users.py
This PR has a high priority because restores the project work.
=> Fixed merge bugs

.gitignore, monolith/app.py, monolith/config/app.conf, monolith/database.py, monolith/templates/create_restaurant.html, monolith/templates/create_user.html, monolith/templates/login.html, monolith/utils/SendMail.py, monolith/views/restaurants.py, monolith/views/users.py
This PR includes some fix to UI, in particular, fix some bug inside the duplicate user and restaurant. In addition, introduce the app.conf inside the app.
The app.conf config is upload on team project https://github.com/orgs/GreyTeam2020/projects/1#column-11373439
=> introduce the template of app.conf and managed error inside the UI from sql exception

monolith/templates/restaurantsheet.html
restaurant profile gui: added other info required by a storm
=> restaurant profile gui: added other info required by a storm

monolith/static/styles/app.css, monolith/templates/booking.html, monolith/templates/footer.html, monolith/templates/header.html, monolith/templates/index.html, monolith/templates/navbar.html, monolith/templates/navbar/admin.html, monolith/templates/navbar/anonymous.html, monolith/templates/navbar/customer.html, monolith/templates/navbar/health.html, monolith/templates/navbar/operator.html, monolith/templates/restaurants.html, monolith/templates/restaurantsheet.html, monolith/templates/sendemailok.html, monolith/templates/testtpl.html, monolith/templates/users.html, monolith/views/home.py
Adapted GUI to Composite Pattern and functional changes
Restaurant list is now public in index
=> Adapted GUI to Composite Pattern and functional changes

monolith/static/js/app.js, monolith/templates/index.html, monolith/templates/navbar.html, monolith/templates/restaurantsheet.html, monolith/views/restaurants.py
searchbar and book from restaurant view
=> searchbar and book from restaurant view

monolith/templates/restaurantsheet.html, monolith/views/restaurants.py
=> bug corretti

Dockerfile
=> Fixed docker image

monolith/templates/header.html, monolith/templates/index.html, monolith/templates/login.html, monolith/templates/navbar.html
Doc: https://bootswatch.com/cosmo/
HTML link to import it without static file
```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/cosmo/bootstrap.min.css"
integrity="sha384-5QFXyVb+lrCzdN228VS3HmzpiE7ZVwLQtkt+0d9W43LQMzz4HBnnqvVxKg6O+04d" crossorigin="anonymous">
```
=> This is a draft version of porting UI on cosmo bootstrap

monolith/static/js/app.js, monolith/templates/all_restaurants.html, monolith/templates/create_restaurant.html, monolith/templates/create_user.html, monolith/templates/footer.html, monolith/templates/header.html, monolith/templates/index.html, monolith/templates/my_menu.html, monolith/templates/my_photogallery.html, monolith/templates/my_reservations.html, monolith/templates/my_restaurant_data.html, monolith/templates/navbar.html, monolith/templates/navbar/customer.html, monolith/templates/navbar/health.html, monolith/templates/navbar/operator.html, monolith/templates/report_positive.html, monolith/templates/restaurantsheet.html, monolith/templates/user_reservations.html, monolith/views/__init__.py, monolith/views/health.py, monolith/views/restaurants.py, monolith/views/users.py
In this PR there is 
- the migration from Classic to Cosmo
- all the pages needed by the navbars (without logic)
- new Health view for health authority
=> Migration to Bootstrap Cosmo and new pages (all)

monolith/app.py, monolith/auth.py, monolith/database.py, monolith/templates/list_reservations.html, monolith/views/auth.py, monolith/views/restaurants.py, monolith/views/users.py
@vincenzopalazzo I had only one conflict with your fix in check role in not None, but I think I resolved it.. please check it too in 
in views/auth.py at line 21
=> Operator list reservations

monolith/static/js/app.js, monolith/templates/header.html, monolith/templates/index.html
Added mapView in the index, required by Priority 2 card
@francescofact can you review if this PR is the same as you?
=> added Map View

monolith/forms.py, monolith/templates/restaurantsheet.html, monolith/views/restaurants.py
Inserted more info in the db and in the sheet of the restaurant
=> Restaurant sheet

monolith/tests/fixtures/client.py, monolith/tests/test_forms.py
=> Make the test more stable

monolith/auth.py, monolith/database.py, monolith/forms.py, monolith/templates/index.html, monolith/templates/mark_positive.html, monolith/views/health.py
=> health authority mark people as infected 

monolith/static/styles/app.css, monolith/templates/create_user.html, monolith/templates/footer.html, monolith/templates/index.html, monolith/templates/index_customer.html, monolith/templates/index_health.html, monolith/templates/index_operator.html, monolith/templates/navbar.html, monolith/tests/utils.py, monolith/views/home.py, monolith/views/users.py
=> Remove register restaurant from health autority and refactoring registration customer (TODO)

monolith/forms.py, monolith/services/restaurant_services.py, monolith/services/user_service.py, monolith/templates/header.html, monolith/templates/index.html, monolith/templates/login.html, monolith/templates/photogallery.html, monolith/templates/restaurantsheet.html, monolith/tests/test_forms.py, monolith/tests/test_restaurant_services.py, monolith/tests/test_user_services.py, monolith/views/auth.py, monolith/views/health.py, monolith/views/home.py, monolith/views/restaurants.py, monolith/views/users.py, requirements.txt
=> Remove assertion on html and user hidden tag

.travis.yml, monolith/services/user_service.py, monolith/views/users.py, run-test-dev.sh, tox.ini
=> Increase tests and configured tox

monolith/forms.py, monolith/services/healthy_services.py, monolith/services/user_service.py, monolith/templates/create_user.html, monolith/templates/index_customer.html, monolith/templates/navbar/operator.html, monolith/templates/restaurantsheet.html, monolith/templates/review.html, monolith/views/health.py, monolith/views/home.py, monolith/views/restaurants.py, monolith/views/users.py
and restrict operator to create a restaurant if he has no restaurant
=> Divided Signup

Dockerfile, docker-compose.yaml, monolith/background.py, monolith/utils/send_mail.py, monolith/views/health.py
=> Fixed refused and exception inside the email again

.coveragerc, monolith/database.py, monolith/services/user_service.py, monolith/templates/navbar/operator.html, monolith/tests/test_user_services.py, monolith/views/users.py
=> Refactoring create users flask method and fixed bug  #143

docker-compose.yaml, monolith/app.py, monolith/services/restaurant_services.py, monolith/views/book.py, monolith/views/home.py
=> Static report

monolith/app.py, monolith/background.py
=> Restore coveralls
